/** Given two strings s and t which consist of only lowercase letters.
* String t is generated by random shuffling string s and then add one 
* more letter at a random position.
* 
* Find the letter that was added in t.
* 
* Example: 
* Input:
* s = "abcd"
* t = "abcde"
* 
* Output:
* e
* 
* Explanation:
* 'e' is the letter that was added.
*/

public class PickTheExtraLetter{
	public static char extraLetter(String s, String t){
		if(s == null || s.length() == 0)
			return t.charAt(0);
		char[] c = new char[256];
		for(int i = 0; i<s.length(); i++)
			c[s.charAt(i)]++;
		for(int i = 0; i<t.length(); i++){
			if(c[t.charAt(i)] == 0)
				return t.charAt(i);
			c[t.charAt(i)]--;
		}
		return '\0';
	}
	public static void main(String[] args) {
		System.out.println(extraLetter("abcd","abcde"));
	}
}